/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppJournalRouteImport } from './routes/app.journal'
import { Route as AppReflectionsRouteImport } from './routes/app.reflections'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppTrendsRouteImport } from './routes/app.trends'
import { Route as AppVoiceRouteImport } from './routes/app.voice'
import { Route as AppEntryIdRouteImport } from './routes/app.entry.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppJournalRoute = AppJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AppRoute,
} as any)
const AppReflectionsRoute = AppReflectionsRouteImport.update({
  id: '/reflections',
  path: '/reflections',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTrendsRoute = AppTrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => AppRoute,
} as any)
const AppVoiceRoute = AppVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => AppRoute,
} as any)
const AppEntryIdRoute = AppEntryIdRouteImport.update({
  id: '/entry/$id',
  path: '/entry/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/app/history': typeof AppHistoryRoute
  '/app/journal': typeof AppJournalRoute
  '/app/reflections': typeof AppReflectionsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/trends': typeof AppTrendsRoute
  '/app/voice': typeof AppVoiceRoute
  '/app/': typeof AppIndexRoute
  '/app/entry/$id': typeof AppEntryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/app/history': typeof AppHistoryRoute
  '/app/journal': typeof AppJournalRoute
  '/app/reflections': typeof AppReflectionsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/trends': typeof AppTrendsRoute
  '/app/voice': typeof AppVoiceRoute
  '/app': typeof AppIndexRoute
  '/app/entry/$id': typeof AppEntryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/app/history': typeof AppHistoryRoute
  '/app/journal': typeof AppJournalRoute
  '/app/reflections': typeof AppReflectionsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/trends': typeof AppTrendsRoute
  '/app/voice': typeof AppVoiceRoute
  '/app/': typeof AppIndexRoute
  '/app/entry/$id': typeof AppEntryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/privacy'
    | '/app/history'
    | '/app/journal'
    | '/app/reflections'
    | '/app/settings'
    | '/app/trends'
    | '/app/voice'
    | '/app/'
    | '/app/entry/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/app/history'
    | '/app/journal'
    | '/app/reflections'
    | '/app/settings'
    | '/app/trends'
    | '/app/voice'
    | '/app'
    | '/app/entry/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/privacy'
    | '/app/history'
    | '/app/journal'
    | '/app/reflections'
    | '/app/settings'
    | '/app/trends'
    | '/app/voice'
    | '/app/'
    | '/app/entry/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/journal': {
      id: '/app/journal'
      path: '/journal'
      fullPath: '/app/journal'
      preLoaderRoute: typeof AppJournalRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reflections': {
      id: '/app/reflections'
      path: '/reflections'
      fullPath: '/app/reflections'
      preLoaderRoute: typeof AppReflectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/trends': {
      id: '/app/trends'
      path: '/trends'
      fullPath: '/app/trends'
      preLoaderRoute: typeof AppTrendsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/voice': {
      id: '/app/voice'
      path: '/voice'
      fullPath: '/app/voice'
      preLoaderRoute: typeof AppVoiceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/entry/$id': {
      id: '/app/entry/$id'
      path: '/entry/$id'
      fullPath: '/app/entry/$id'
      preLoaderRoute: typeof AppEntryIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppHistoryRoute: typeof AppHistoryRoute
  AppJournalRoute: typeof AppJournalRoute
  AppReflectionsRoute: typeof AppReflectionsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTrendsRoute: typeof AppTrendsRoute
  AppVoiceRoute: typeof AppVoiceRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEntryIdRoute: typeof AppEntryIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHistoryRoute: AppHistoryRoute,
  AppJournalRoute: AppJournalRoute,
  AppReflectionsRoute: AppReflectionsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTrendsRoute: AppTrendsRoute,
  AppVoiceRoute: AppVoiceRoute,
  AppIndexRoute: AppIndexRoute,
  AppEntryIdRoute: AppEntryIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
