import { createFileRoute, Link } from "@tanstack/react-router";
import { Send, Sparkle } from "lucide-react";
import { useState } from "react";
import { AiErrorCard, AiLoadingCard, ReflectionCard } from "@/components/ReflectionCard";
import { useEntries } from "@/hooks/useEntries";
import { useSettings } from "@/hooks/useSettings";
import { describeApiError, generateReflection, generateSummary } from "@/services/api";
import { loadEntries, saveEntry } from "@/store/journal";
import { buildMemorySummary, recentEntryTexts } from "@/utils/memory";
import { formatDateTime } from "@/utils/analytics";

export const Route = createFileRoute("/app/reflections")({
  head: () => ({
    meta: [
      { title: "AI Reflections — MindVault" },
      {
        name: "description",
        content: "Chat-style supportive reflections generated by your own local Gemma companion.",
      },
      { property: "og:title", content: "AI Reflections — MindVault" },
      { property: "og:description", content: "Reflections and summaries from your local AI companion." },
    ],
  }),
  component: ReflectionsPage,
});

const PROMPTS = [
  "How are you feeling today?",
  "What made you smile today?",
  "What's stressing you lately?",
  "What's something you're grateful for?",
];

interface Turn {
  id: string;
  entry: string;
  reflection?: string;
  at: string;
}

function ReflectionsPage() {
  const { entries } = useEntries();
  const { settings } = useSettings();
  const [draft, setDraft] = useState("");
  const [turns, setTurns] = useState<Turn[]>([]);
  const [busy, setBusy] = useState<null | "reflect" | "summarize">(null);
  const [summary, setSummary] = useState("");
  const [error, setError] = useState<{ message: string; retry: () => void } | null>(null);

  const past = entries.filter((e) => e.reflection).slice(0, 5);

  const send = async (text: string) => {
    const value = text.trim();
    if (!value) return;
    setDraft("");
    setError(null);
    // Save locally first, always.
    const saved = saveEntry({ text: value, source: "text" });
    const turn: Turn = { id: saved.id, entry: value, at: new Date().toISOString() };
    setTurns((prev) => [...prev, turn]);
    setBusy("reflect");
    try {
      const all = loadEntries();
      const response = await generateReflection({
        entry: value,
        memory_summary: buildMemorySummary(all.filter((e) => e.id !== saved.id)),
        recent_entries: recentEntryTexts(all, saved.id, 3),
      });
      setTurns((prev) =>
        prev.map((t) => (t.id === turn.id ? { ...t, reflection: response.reflection } : t)),
      );
      saveEntry({
        id: saved.id,
        text: value,
        reflection: { text: response.reflection, createdAt: new Date().toISOString() },
      });
    } catch (err) {
      setError({ message: describeApiError(err), retry: () => send(value) });
    } finally {
      setBusy(null);
    }
  };

  const summarizeAll = async () => {
    setError(null);
    const texts = loadEntries()
      .slice(0, 12)
      .map((e) => e.text.trim())
      .filter(Boolean);
    if (!texts.length) return;
    setBusy("summarize");
    try {
      const response = await generateSummary({ entries: texts });
      setSummary(response.summary);
    } catch (err) {
      setError({ message: describeApiError(err), retry: summarizeAll });
    } finally {
      setBusy(null);
    }
  };

  return (
    <div className="mx-auto flex max-w-3xl flex-col gap-5">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <h1 className="font-display text-2xl font-semibold">AI reflections</h1>
          <p className="text-sm text-muted-foreground">
            Supportive reflections from your local companion — not a therapist or medical professional.
          </p>
        </div>
        <button
          type="button"
          onClick={summarizeAll}
          disabled={busy !== null}
          className="rounded-2xl border border-border/70 bg-card/50 px-4 py-2.5 text-sm hover:bg-card disabled:opacity-60"
        >
          Summarize Journal
        </button>
      </div>

      {summary && (
        <article className="glass animate-rise rounded-3xl p-6">
          <h2 className="font-display text-lg font-semibold">Journal summary</h2>
          <p className="mt-3 whitespace-pre-wrap text-sm leading-relaxed">{summary}</p>
        </article>
      )}

      <div className="space-y-4">
        {turns.length === 0 && past.length === 0 && !busy && (
          <div className="glass rounded-3xl p-6 text-center">
            <span className="brand-surface mx-auto flex size-12 items-center justify-center rounded-2xl">
              <Sparkle className="size-5" />
            </span>
            <p className="mt-4 text-sm text-muted-foreground">
              Share what's on your mind. Your words are saved on this device before anything is sent to
              your local model.
            </p>
          </div>
        )}

        {past.length > 0 && turns.length === 0 && (
          <section className="space-y-3">
            <p className="text-xs uppercase tracking-wide text-muted-foreground">Earlier reflections</p>
            {past.map((entry) => (
              <Link
                key={entry.id}
                to="/app/entry/$id"
                params={{ id: entry.id }}
                className="glass block rounded-3xl p-5 transition-transform hover:-translate-y-0.5"
              >
                <p className="text-xs text-muted-foreground">{formatDateTime(entry.createdAt)}</p>
                <p className="mt-1 line-clamp-2 text-sm">{entry.reflection?.text}</p>
              </Link>
            ))}
          </section>
        )}

        {turns.map((turn) => (
          <div key={turn.id} className="space-y-3">
            <div className="flex justify-end">
              <div className="max-w-[85%] rounded-3xl rounded-br-lg bg-primary px-4 py-3 text-sm text-primary-foreground">
                <p className="whitespace-pre-wrap">{turn.entry}</p>
                <p className="mt-1.5 text-[10px] opacity-70">{formatDateTime(turn.at)}</p>
              </div>
            </div>
            {turn.reflection && (
              <ReflectionCard reflection={turn.reflection} animate={settings.typingAnimation} />
            )}
          </div>
        ))}

        {busy === "reflect" && <AiLoadingCard label="Your local AI companion is reflecting..." />}
        {busy === "summarize" && <AiLoadingCard label="Your local AI is summarizing your journal..." />}
        {error && <AiErrorCard message={error.message} onRetry={error.retry} />}
      </div>

      <div className="sticky bottom-24 lg:bottom-4">
        <div className="mb-3 flex flex-wrap gap-2">
          {PROMPTS.map((prompt) => (
            <button
              key={prompt}
              type="button"
              onClick={() => setDraft(prompt)}
              className="rounded-full border border-border/70 bg-card/50 px-3 py-1.5 text-xs text-muted-foreground hover:text-foreground"
            >
              {prompt}
            </button>
          ))}
        </div>
        <form
          onSubmit={(event) => {
            event.preventDefault();
            send(draft);
          }}
          className="glass flex items-end gap-2 rounded-3xl p-2"
        >
          <textarea
            value={draft}
            onChange={(event) => setDraft(event.target.value)}
            onKeyDown={(event) => {
              if (event.key === "Enter" && !event.shiftKey) {
                event.preventDefault();
                send(draft);
              }
            }}
            rows={2}
            placeholder="What's on your mind?"
            className="min-h-12 flex-1 resize-none bg-transparent px-3 py-2.5 text-sm outline-none"
          />
          <button
            type="submit"
            disabled={busy !== null || !draft.trim()}
            aria-label="Send"
            className="brand-surface flex size-11 shrink-0 items-center justify-center rounded-2xl disabled:opacity-50"
          >
            <Send className="size-4" />
          </button>
        </form>
      </div>
    </div>
  );
}
