import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft } from "lucide-react";
import { PrivacyBadges } from "@/components/PrivacyBanner";
import { apiBaseUrl } from "@/services/api";

export const Route = createFileRoute("/privacy")({
  head: () => ({
    meta: [
      { title: "How Privacy Works — MindVault" },
      {
        name: "description",
        content:
          "MindVault keeps journal entries in your browser's local storage and sends AI requests only to your own local FastAPI + Gemma backend.",
      },
      { property: "og:title", content: "How Privacy Works — MindVault" },
      {
        property: "og:description",
        content: "Local storage, local inference: exactly where your MindVault data travels.",
      },
    ],
  }),
  component: PrivacyPage,
});

function PrivacyPage() {
  return (
    <main className="mx-auto max-w-3xl px-5 py-10">
      <Link
        to="/"
        className="inline-flex items-center gap-2 text-sm text-muted-foreground transition-colors hover:text-foreground"
      >
        <ArrowLeft className="size-4" /> Back
      </Link>

      <h1 className="mt-6 font-display text-4xl font-semibold">How privacy works</h1>
      <p className="mt-3 text-muted-foreground">
        Your journal data stays on your device and AI processing is performed locally.
      </p>

      <PrivacyBadges className="mt-6" />

      <section className="glass mt-8 rounded-3xl p-6">
        <h2 className="font-display text-xl font-semibold">Where your entries live</h2>
        <p className="mt-2 text-sm text-muted-foreground">
          Entries, moods, tags, reflections and summaries are written to this browser's local storage on
          this device. There is no cloud database, no account, and no third-party analytics.
        </p>
      </section>

      <section className="glass mt-4 rounded-3xl p-6">
        <h2 className="font-display text-xl font-semibold">Where AI requests go</h2>
        <pre className="mt-3 overflow-x-auto rounded-2xl border border-border/60 bg-card/50 p-4 text-xs leading-relaxed text-muted-foreground">
{`MindVault (this browser)
   ↓  POST /reflect · POST /summarize
FastAPI  ${apiBaseUrl}
   ↓  HTTP
llama.cpp  http://127.0.0.1:8080
   ↓
Gemma 3 4B-IT Q4_K_M  ·  local GPU inference`}
        </pre>
        <p className="mt-3 text-sm text-muted-foreground">
          MindVault never calls a cloud AI provider. The only AI request path is the local one above, and
          the browser never talks to llama.cpp directly.
        </p>
      </section>

      <section className="glass mt-4 rounded-3xl p-6">
        <h2 className="font-display text-xl font-semibold">What we send to the model</h2>
        <p className="mt-2 text-sm text-muted-foreground">
          Only the entry you're reflecting on, a short memory summary computed on your device, and your
          most recent two or three entries. Your full history is never uploaded — not even to your own
          backend.
        </p>
      </section>

      <section className="glass mt-4 rounded-3xl p-6">
        <h2 className="font-display text-xl font-semibold">Honest limits</h2>
        <p className="mt-2 text-sm text-muted-foreground">
          MindVault is not fully on-device: reflections are generated by a separate local service you run
          yourself. Anyone with access to this device or that service can read what is sent. MindVault
          offers supportive reflections, not medical or clinical advice.
        </p>
      </section>

      <div className="mt-8">
        <Link
          to="/app/journal"
          className="brand-surface inline-flex rounded-2xl px-6 py-3.5 text-sm font-medium transition-transform hover:-translate-y-0.5"
        >
          Start Journaling
        </Link>
      </div>
    </main>
  );
}
