/**
 * Centralized API service for the local MindVault backend.
 *
 * Flow: React -> FastAPI (http://127.0.0.1:8000) -> llama.cpp -> Gemma 3 4B-IT
 * The frontend NEVER talks to llama.cpp or any cloud AI provider directly.
 * Every backend request in the app must go through this file.
 */

const API_URL = import.meta.env.VITE_API_URL || "http://127.0.0.1:8000";

export const apiBaseUrl = API_URL;

export interface HealthResponse {
  status: string;
  model?: string;
  runtime?: string;
  privacy?: string;
}

export interface ReflectRequest {
  entry: string;
  memory_summary: string;
  recent_entries: string[];
}

export interface ReflectResponse {
  reflection: string;
}

export interface SummarizeRequest {
  entries: string[];
}

export interface SummarizeResponse {
  summary: string;
}

export type ApiErrorKind = "offline" | "unreachable" | "timeout" | "server" | "empty" | "unknown";

export class ApiError extends Error {
  kind: ApiErrorKind;
  status?: number;

  constructor(kind: ApiErrorKind, message: string, status?: number) {
    super(message);
    this.name = "ApiError";
    this.kind = kind;
    this.status = status;
  }
}

export const OFFLINE_SAVE_MESSAGE =
  "Your journal entry is safely saved on this device. Your local AI companion is temporarily unavailable.";

export function describeApiError(error: unknown): string {
  if (error instanceof ApiError) {
    switch (error.kind) {
      case "offline":
        return "You appear to be offline. Journaling keeps working — AI reflection needs your local companion.";
      case "unreachable":
        return `Couldn't reach your local AI companion at ${API_URL}. Make sure the FastAPI backend and llama.cpp are running.`;
      case "timeout":
        return "Your local AI companion took too long to respond. It may still be loading the Gemma model.";
      case "server":
        return `Your local AI companion responded with an error (${error.status ?? 500}). Check the FastAPI logs.`;
      case "empty":
        return "Your local AI companion returned an empty response. Try again in a moment.";
      default:
        return error.message;
    }
  }
  return "Something unexpected happened while contacting your local AI companion.";
}

async function request<T>(path: string, init: RequestInit = {}, timeoutMs = 120_000): Promise<T> {
  if (typeof navigator !== "undefined" && navigator.onLine === false) {
    throw new ApiError("offline", "Browser is offline");
  }

  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);

  let response: Response;
  try {
    response = await fetch(`${API_URL}${path}`, {
      ...init,
      signal: controller.signal,
      headers: { "Content-Type": "application/json", ...(init.headers ?? {}) },
    });
  } catch (error) {
    if (error instanceof DOMException && error.name === "AbortError") {
      throw new ApiError("timeout", "Request timed out");
    }
    throw new ApiError("unreachable", "Local backend unreachable");
  } finally {
    clearTimeout(timer);
  }

  if (!response.ok) {
    throw new ApiError("server", `Backend returned ${response.status}`, response.status);
  }

  const text = await response.text();
  if (!text.trim()) {
    throw new ApiError("empty", "Empty response body");
  }

  try {
    return JSON.parse(text) as T;
  } catch {
    throw new ApiError("unknown", "Backend returned a malformed response");
  }
}

/** GET /health — is the local FastAPI + Gemma stack available? */
export async function checkHealth(): Promise<HealthResponse> {
  return request<HealthResponse>("/health", { method: "GET" }, 8_000);
}

/** POST /reflect — supportive reflection generated by the local Gemma model. */
export async function generateReflection(payload: ReflectRequest): Promise<ReflectResponse> {
  const data = await request<ReflectResponse>("/reflect", {
    method: "POST",
    body: JSON.stringify(payload),
  });
  if (!data || typeof data.reflection !== "string" || !data.reflection.trim()) {
    throw new ApiError("empty", "Backend returned no reflection");
  }
  return data;
}

/** POST /summarize — journal summary generated by the local Gemma model. */
export async function generateSummary(payload: SummarizeRequest): Promise<SummarizeResponse> {
  const data = await request<SummarizeResponse>("/summarize", {
    method: "POST",
    body: JSON.stringify(payload),
  });
  if (!data || typeof data.summary !== "string" || !data.summary.trim()) {
    throw new ApiError("empty", "Backend returned no summary");
  }
  return data;
}
